### ISSUE TITLE
배치파일 수정 요청.

### ISSUE THREAD

**Issue by kbuwel** [N01N9/AniTTS-Builder-One-Click#1]
배포하신 분의 환경을 잘 모릅니다.
README.md에 배포하신 분의 환경을 자세하게 적어 주시면 감사하겠습니다.
90 시리즈 gpu와 cuda 12.1 사용한다는 것 외에 어떤 환경인지 자세한 내용이 없어 문제 해결에 어려움이 있습니다.
제 문제를 설명하면 다음과 같습니다.
Install-AniTTS-Builder-webUI.bat
이 파일의 문제인지 제 인터넷 문제인지 잘 모르겠습니다만 pc 2대에서 실행했습니다.
cudnn 9x를 인식하지 못합니다.
cuda 12.1을 설치했습니다.
windows 10과 11을 사용하는 시스템이고 gtx와 rtx 시스템입니다.
제가 시작키와 r키를 눌러 실행창에 C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\cudnn_version.h 입력해 봤습니다.
제가 실행창에 경로 입력하면 실행이 잘 되었습니다.
하지만 배치파일을 실행하면 cudnn을 찾지 못하였습니다.
억지로 실행해도 다음 문제가 발생합니다.
ffmpeg를 다운받았지만 압축 푸는 게 문제가 있습니다.
반디집 설치했습니다.
lib 폴더에 ffmpeg 파일이 있는것을 확인했고 반디집으로 압축도 풀어봤습니다.
배치파일로 압축푸는 게 문제가 있지 제가 직접 반디집으로 압축을 풀면 잘 풀립니다.
다음으로 콘다 문제입니다.
콘다 다운 받는 것이 문제가 있는거 같습니다.
배치 파일에서 콘다 다운 받는 것을 실패합니다.
제가 배치파일을 열어 url을 복사해 크롬에 입력하면 콘다가 다운받아집니다.
콘다 문제로 main.py을 명령 프롬프트에서 강제로 실행했지만 배경음 제거에서 문제가 발생합니다.
무슨 dll 파일이 없다는 문제입니다.
콘다가 다운 받지 못해 생긴 문제인거 같다는 생각입니다.

**Comment by wpqlRhc** [comment]
수정되었습니다. 해결완료.

**Comment by N01N9** [comment]
수정완료.

**Comment by kbuwel** [comment]
모델 다운 받는 부분에서 오류가 발생합니다.
로그는 다음과 같습니다.
Traceback (most recent call last):                                                                                      
  File "C:\Users\Administrator\AniTTS-Builder-One-Click\AniTTS-Builder-webUI\initialize.py", line 14, in <module>       
    file_path = hf_hub_download(repo_id=repo_id, filename=filename, local_dir=destination_folder)                       
  File "C:\Users\Administrator\AniTTS-Builder-One-Click\lib\Miniconda3\envs\AniTTS-Builder2-webUI\lib\site-packages\hugg
ingface_hub\utils\_validators.py", line 114, in _inner_fn                                                               
    return fn(*args, **kwargs)                                                                                          
  File "C:\Users\Administrator\AniTTS-Builder-One-Click\lib\Miniconda3\envs\AniTTS-Builder2-webUI\lib\site-packages\hugg
ingface_hub\file_download.py", line 842, in hf_hub_download                                                             
    return _hf_hub_download_to_local_dir(                                                                               
  File "C:\Users\Administrator\AniTTS-Builder-One-Click\lib\Miniconda3\envs\AniTTS-Builder2-webUI\lib\site-packages\hugg
ingface_hub\file_download.py", line 1138, in _hf_hub_download_to_local_dir                                              
    _download_to_tmp_and_move(                                                                                          
  File "C:\Users\Administrator\AniTTS-Builder-One-Click\lib\Miniconda3\envs\AniTTS-Builder2-webUI\lib\site-packages\hugg
ingface_hub\file_download.py", line 1533, in _download_to_tmp_and_move                                                  
    with incomplete_path.open("ab") as f:                                                                               
  File "C:\Users\Administrator\AniTTS-Builder-One-Click\lib\Miniconda3\envs\AniTTS-Builder2-webUI\lib\pathlib.py", line 
1119, in open                                                                                                           
    return self._accessor.open(self, mode, buffering, encoding, errors,                                                 
FileNotFoundError: [Errno 2] No such file or directory: 'module\\MSST_WebUI\\pretrain\\vocal_models\\.cache\\huggingface
\\download\\All_Models\\vocal_models\\Kim_MelBandRoformer.ckpt.87201f4d31afb5bc79993230fc49446918425574db48c01c405e44f36
5c7559e.incomplete'                                                                                                     
Press any key to continue . . .

**Comment by N01N9** [comment]
저도 전문가는 아닌지라 정확한 원인은 저도 파악이 힘듭니다. 죄송합니다. lib폴더와 webui폴더 삭제 후 관리자 권한으로 다시 시도해보시는것을 추천합니다. 만약 위 방법 시도 후에도 해결되지 않는다면 그 이전단계는 정상적으로 수행되었다는 가정하에 오류가 난 파트와 그 이후파트를 수동으로 진행하는것이 최선일 듯 합니다.

**Comment by kbuwel** [comment]
제가 배치 파일에 대한 건 잘 모릅니다.
위에 모델 다운 받는 것은 어떻게 해결될듯한데 main.bat 이게 문제입니다.
Activating Conda environment...                                                                                         
'conda' is not recognized as an internal or external command,                                                           
operable program or batch file.                                                                                         
Failed to activate the Conda environment.                                                                               
Press any key to continue . . .                                                                                         
이 문제는 AniTTS-Builder-webUI 폴더를 삭제하고 lib 폴더를 삭제해도 해결 될 수 없는 문제 같습니다.
제가 코딩과 배치파일을 잘 모르기에 그냥 추측입니다.
conda 가상환경을 분명 설정했을겁니다.
아나콘다를 많이 접해봤기에 할 수 있는 추측입니다.
Install-AniTTS-Builder-webUI.bat에서 미니 콘다를 다운받았습니다.
그리고 가상 환경을 설정했겠죠.
그런데 여기서 문제가 발생한거 같다는 생각입니다.
가상 환경을 불러와야하는데 불러오지를 않았고 위의 오류가 표시되지 않았나 추측해 봅니다.
이 문제는 main.bat를 수정해야만 해결 될거 같습니다.
많은 분들이 이 프로젝트를 다운 받았을건데 다른 분들도 이런 문제가 있는지 살펴봐야할듯합니다.

**Comment by N01N9** [comment]
콘다 환경변수 설정해보세요

**Comment by kbuwel** [comment]
conda 다운로드 경로가 잘못되어있다는 것을 알려드립니다.
main.bat을 열면 conda 가상환경을 찾지 못한다고 이전 댓글에 적었습니다.
windows의 바탕화면 계정명으로 들어가면 anaconda3 폴더가 있습니다.
envs\AniTTS-Builder2-webUI에 보면 수 많은 폴더와 파일이 나옵니다.
이 것들은 다음 폴더에 들어있어야합니다.
Install-AniTTS-Builder-webUI.bat를 실행하면 다음 폴더가 생성됩니다.
lib\Miniconda3\envs\AniTTS-Builder2-webUI
이 곳에 anaconda3\envs\AniTTS-Builder2-webUI 내의 폴더와 파일들을 넣어줘야합니다.
main.bat를 실행하면 웹브라우저가 문제 없이 실행됩니다.
문제가 발생하는 분들이 계시면 이 댓글 참고해서 경로 수정해서 사용하시라고 적어 봅니다.
